#!/bin/bash -

# wait for the test to start
for node in $(seq 1 4)
do
    while (! test -f persist/$node/var/log/iperf.log)
    do
        sleep 1
    done
done

multitail persist/1/var/log/iperf.log  persist/2/var/log/iperf.log \
    persist/3/var/log/iperf.log  persist/4/var/log/iperf.log
