TOP_DIR=..

DEMO_ID=6

NEM_XML=

TEMPLATE_OTESTPOINTD=otestpointd.xml.template

PLATFORMS= \
 platform1.xml \
 platform2.xml \
 platform3.xml \
 platform4.xml

GENERATED_EVENTDAEMONS= \
 eventdaemon1.xml \
 eventdaemon2.xml \
 eventdaemon3.xml \
 eventdaemon4.xml

GENERATED_GPSDLOCATIONAGENTS= \
 gpsdlocationagent1.xml \
 gpsdlocationagent2.xml \
 gpsdlocationagent3.xml \
 gpsdlocationagent4.xml

GENERATED_MGENINPUTS=

GENERATED_ROUTINGCONFS= \
 routing1.conf \
 routing2.conf \
 routing3.conf \
 routing4.conf

GENERATED_OTESTPOINTDS= \
 otestpointd1.xml \
 otestpointd2.xml \
 otestpointd3.xml \
 otestpointd4.xml

GENERATED_OTESTPOINTRECORDERS= \
 otestpoint-recorder1.xml \
 otestpoint-recorder2.xml \
 otestpoint-recorder3.xml \
 otestpoint-recorder4.xml

GENERATED_EXTRA= \
 antennaprofilemanifest.xml

include ../rules.mk
