TOP_DIR=..

DEMO_ID=1

NEM_XML=rfpipenem.xml

GENERATED_PLATFORMS=             \
 platform1.xml                   \
 platform2.xml                   \
 platform3.xml                   \
 platform4.xml                   \
 platform5.xml                   \
 platform6.xml                   \
 platform7.xml                   \
 platform8.xml                   \
 platform9.xml                   \
 platform10.xml               

GENERATED_EVENTDAEMONS=          \
 eventdaemon1.xml                \
 eventdaemon2.xml                \
 eventdaemon3.xml                \
 eventdaemon4.xml                \
 eventdaemon5.xml                \
 eventdaemon6.xml                \
 eventdaemon7.xml                \
 eventdaemon8.xml                \
 eventdaemon9.xml                \
 eventdaemon10.xml

GENERATED_GPSDLOCATIONAGENTS=    \
 gpsdlocationagent1.xml          \
 gpsdlocationagent2.xml          \
 gpsdlocationagent3.xml          \
 gpsdlocationagent4.xml          \
 gpsdlocationagent5.xml          \
 gpsdlocationagent6.xml          \
 gpsdlocationagent7.xml          \
 gpsdlocationagent8.xml          \
 gpsdlocationagent9.xml          \
 gpsdlocationagent10.xml

GENERATED_MGENINPUTS=

GENERATED_ROUTINGCONFS=           \
 routing1.conf                    \
 routing2.conf                    \
 routing3.conf                    \
 routing4.conf                    \
 routing5.conf                    \
 routing6.conf                    \
 routing7.conf                    \
 routing8.conf                    \
 routing9.conf                    \
 routing10.conf                   

NO-%:
	touch $@

GENERATED_EXTRA=           \
 NO-host-emaneeventservice 


include ../rules.mk

