TOP_DIR=..

DEMO_ID=5

NEM_XML=

PLATFORMS=                      \
 platform1.xml                  \
 platform2.xml                  \
 platform3.xml                  \
 platform4.xml                  

GENERATED_EVENTDAEMONS=         \

GENERATED_GPSDLOCATIONAGENTS=    

GENERATED_MGENINPUTS=

GENERATED_ROUTINGCONFS=          

include ../rules.mk

