TOP_DIR=..

DEMO_ID=5

NEM_XML=

PLATFORMS= \
 platform1.xml \
 platform2.xml \
 platform3.xml \
 platform4.xml

GENERATED_EVENTDAEMONS=

GENERATED_GPSDLOCATIONAGENTS=

GENERATED_MGENINPUTS=

GENERATED_ROUTINGCONFS=

GENERATED_OTESTPOINTRECORDERS= \
 otestpoint-recorder1.xml \
 otestpoint-recorder2.xml \
 otestpoint-recorder3.xml \
 otestpoint-recorder4.xml

include ../rules.mk
