#!/bin/bash -

if [ $# -ne 2 ]
   then
    "host-prestop: invalid number of arguments" >&2 
    exit 1
fi

demo=$1
count=$2

echo "Running host-prestop demo $demo node count $2"

echo "Collecting statistics and configuration"
emanesh localhost show >  persist/host/var/log/emane.show
emanesh localhost get stat '*' all >  persist/host/var/log/emane.stats
emanesh localhost get table '*' all >  persist/host/var/log/emane.tables
emanesh localhost get config '*' all >  persist/host/var/log/emane.config


echo "Stopping all otestpointd instances"
kill -QUIT $(find persist -name otestpointd*.pid -exec cat {} \;)

echo "Stopping all otestpoint-recorder instances"
kill -QUIT $(find persist -name otestpoint-recorder*.pid -exec cat {} \;)
