TOP_DIR=..

NODE_COUNT=7

DEMO_ID=2

NEM_XML=

PLATFORMS=platform.xml

GENERATED_PLATFORMS=             

GENERATED_EVENTDAEMONS=          

GENERATED_GPSDLOCATIONAGENTS=    

GENERATED_MGENINPUTS=

GENERATED_ROUTINGCONFS=           \
 routing1.conf                    \
 routing2.conf                    \
 routing3.conf                    \
 routing4.conf                    \
 routing5.conf                    \
 routing6.conf                    \
 routing7.conf                    \
 routing8.conf                    \
 routing9.conf                    \
 routing10.conf                   

include ../rules.mk

